/*
  Copyright (c) 2025 Easytime Technology Co., Ltd. See LICENSE.md.
*/

#include "/Engine/Public/Platform.ush"

#include "../ThirdParty/Public/constants.ush"
#include "../ThirdParty/Public/unpacking.ush"

float4x4 local_to_world;
float4x4 local_to_view;
float4x4 local_to_clip;
uint global_offset;
uint num_splats;
uint sh_degree;
uint sh_num_triplets;
float two_focal_length;
float opacity;
float brightness;
float contrast;
float3 color_tint;
float3 world_camera_origin;
float3 pos_scale_cm;
float3 pos_min_cm;
uint bUseFloatPositions;
uint bUseFloatCovariances;

Buffer<uint> positions;
Buffer<float4> positions_float;
Buffer<uint2> covariances;
Buffer<float4> covariances_float;
Buffer<float4> colors;
Buffer<float3> sh_coefficients;
RWBuffer<uint> out_global_indices;
RWBuffer<uint> out_global_distances;
RWBuffer<float4> out_global_world_centers;
RWBuffer<float4> out_global_transforms;
RWBuffer<float4> out_global_colors;

#include "../ThirdParty/Public/gather_proxy_render_data_to_global.cs.ush"
